baseURL = "https://yanitrevino.github.io/portfolio/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "C-MOOR Student"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
